#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ "$SHLVL" -eq 1 && ! -o LOGIN && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

# xfce4-terminal is capable of displaying 256 colors, but doesn't set the
# environment variable TERM accordingly. We therefore do it by ourselves.
# The same applies to the MSYS2 terminal.
if [[ "$COLORTERM" == 'xfce4-terminal' || "$OSTYPE" == 'msys' ]]; then
  export TERM=xterm-256color
fi
