#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# Select first match on ambiguous completion
setopt menu_complete

# Emacs-like navigation inside menuselect (C-f and C-b are already available)
zmodload zsh/complist
bindkey -M menuselect '^n' down-line-or-search
bindkey -M menuselect '^p' up-line-or-search

# Aliases
alias cp='cp -i'
alias mv='mv -i'
alias rm='rm -i'
alias ll='ls -l'
alias la='ls -la'
#alias emacs="XMODIFIERS='' emacs"
#alias skype="XMODIFIERS='' skype"

# git stuff
alias gia='git add'
alias gib='git branch'
alias gic='git commit'
alias gid='git diff'
alias gif='git fetch -p'
alias gih='git stash'
alias gik='git checkout'
alias gil='git log'
alias gim='git merge'
alias gip='git cherry-pick'
alias gipl='git pull'
alias gips='git push'
alias gir='git rebase'
alias gis='git status'
